apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-learning
  namespace: default
  labels:
    app: cicd-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-learning
  template:
    metadata:
      labels:
        app: cicd-learning
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          image: ghcr.io/skinner84/cicd_learning:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            runAsNonRoot: true
            runAsUser: 65532
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
