name: CD - Deploy to k3s (placeholder)
on:
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Placeholder
        run: echo "Milestone 2 will implement deploy/verify."

